# Pandas

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 24.3 MB/s  0:00:00m0:00:010:01
Downloading numpy-2.4.4-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 42.8 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.4 pandas-3.0.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

# a partir de una lista, tupla y dict

In [6]:
data = [['Juan', 25], ['Pedro', 34], ['Luis', 45]]

# crear el dataframe
df = pd.DataFrame(data, columns=['Nombre', 'Edad'])

In [7]:
df

  Nombre  Edad
0   Juan    25
1  Pedro    34
2   Luis    45

In [8]:
# Crear en Base a un diccionario
data = {
    'Nombre': ['Juan', 'Pedro', 'Luis'],
    'Edad': [25, 26, 34]
}

df = pd.DataFrame(data)

df

  Nombre  Edad
0   Juan    25
1  Pedro    26
2   Luis    34

In [13]:
# leer un archivo csv

df = pd.read_csv('utils/data/data.csv')

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [ ]:
# leemos un archivo sin extension, y con seprador distinto a la coma

df = pd.read_csv('utils/data/data', sep = '|')

df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [4]:
# leer un archivo csv, sin cabecera

df = pd.read_csv('utils/data/data_without_header',
                 sep =',',
                 header=None,
                 names = ['Nombre', 'Edad', 'Ciudad']
                 )

df

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [5]:
# lectura de un archivo JSON
df = pd.read_json('./utils/data/data.json')

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

# Metodos con Dataframe

In [6]:
df.describe()

       edad
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [11]:
df.head() # primeros valors

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [14]:
df.tail(2)

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [15]:
# lista los nombres de columnas
df.columns

Index(['nombre', 'edad', 'ciudad'], dtype='str')

In [16]:
# Busca los indices
df.index

RangeIndex(start=0, stop=3, step=1)

In [19]:
# Contabilizar
df.count()

nombre    3
edad      3
ciudad    3
dtype: int64

# Acceder a valores con DF

In [26]:
# Una sola columna
df['ciudad']

df[['ciudad', 'edad']]

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [ ]:
# Por un indice
print(df.loc[0])

nombre      Juan
edad          25
ciudad    Madrid
Name: 0, dtype: object

In [25]:
print(df.loc[[0,2]])

  nombre  edad   ciudad
0   Juan    25   Madrid
2  Pedro    35  Sevilla

In [28]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [30]:
print(df[df['edad']>25])

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

# Agregaciones

In [36]:
# Agrpar datos por columnas y usar funciones

data = {
    'Grupo': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Valor': [10, 20, 15, 25, 12, 18]
}

df = pd.DataFrame(data)

# calcular el promedio por grupo
promedio_por_grupo = df.groupby('Grupo').mean()
print(promedio_por_grupo)

# calcular la suma por grupo
suma_por_grup = df.groupby('Grupo').sum()
print(suma_por_grup)

           Valor
Grupo
A      12.333333
B      21.000000
       Valor
Grupo
A         37
B         63

In [37]:
df = pd.read_csv('utils/data/data', sep='|')

df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [ ]:
# eliminar las filas con NaN
df_sin_na = df.dropna()
print(df_sin_na)

print('\n')

# reemplazar los valores Nan
df_completo = df.fillna(value=0)
print(df_completo)

print('\n')

# Eliminar solo la fila
df_sin_na_2 = df.dropna(subset=['ciudad'])
print(df_sin_na_2)

  nombre  edad     ciudad
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla


  nombre  edad     ciudad
0   Juan   0.0     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla


  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

# Funciones en un Dataframe

In [43]:
data = {
    'A': [1, 2, 3, 4],
    'B': [6, 7, 8, 9]
}

df = pd.DataFrame(data)

df

   A  B
0  1  6
1  2  7
2  3  8
3  4  9

In [44]:
df['A_doble'] = df['A'].apply(lambda x: x*2)

df

   A  B  A_doble
0  1  6        2
1  2  7        4
2  3  8        6
3  4  9        8

In [ ]:
def multiplo2(x):
    return x*2

df['A_doble2'] = df['A'].apply(multiplo2)

df

   A  B  A_doble  A_doble2
0  1  6        2         2
1  2  7        4         4
2  3  8        6         6
3  4  9        8         8

In [46]:
df['suma'] = df.apply(lambda row: row['A'] + row['B'], axis = 1)

df

   A  B  A_doble  A_doble2  suma
0  1  6        2         2     7
1  2  7        4         4     9
2  3  8        6         6    11
3  4  9        8         8    13

In [ ]:
def suma(row):
    ..
    ..
    ..
    
    return row['A'] + row['B']


df['suma_2'] = df.apply(suma, axis=1)

df

   A  B  A_doble  A_doble2  suma  suma_"  suma_2
0  1  6        2         2     7       7       7
1  2  7        4         4     9       9       9
2  3  8        6         6    11      11      11
3  4  9        8         8    13      13      13