# ETL de netflix

In [1]:
import pandas as pd

import sqlalchemy as db

from sqlalchemy import text

In [2]:
# Creare la conexion al motor de BD
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/db_movies_netflix_transact")
# establesco la conexion
conn = engine.connect()

# Cargamos datos a la dimension Moview

In [3]:
query = """
    SELECT 
        movie.movieID as movieID, 
        movie.movieTitle as title, 
        movie.releaseDate as releaseDate, 
        gender.name as gender, 
        person.name as participantName, 
        participant.participantRole as roleparticipant 
    FROM movie 
    INNER JOIN participant ON movie.movieID = participant.movieID
    INNER JOIN person ON person.personID = participant.personID
    INNER JOIN movie_gender ON movie.movieID = movie_gender.movieID
    INNER JOIN gender ON movie_gender.genderID = gender.genderID
"""

In [4]:
movies_data=pd.read_sql(query, con=conn) 

movies_data['movieID'] = movies_data["movieID"].astype('int')

movies_data

,movieID,title,releaseDate,gender,participantName,roleparticipant
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director

In [5]:
# Cargar el archivo awards_movie
movies_award = pd.read_csv('./data/Awards_movie.csv')

movies_award['movieID'] = movies_award["movieID"].astype('int')

movies_award.rename(columns={"Aware":"Award"}, inplace=True)

movies_award

    movieID  IdAward   Award
0  80210920        0   Oscar
1  81157374        1  Grammy
2  80192187        2   Oscar

In [6]:
# Unir las dos tablas (merge)
movie_data = pd.merge(movies_data, 
                      movies_award,
                      left_on='movieID',
                      right_on='movieID')

movie_data

,movieID,title,releaseDate,gender,participantName,roleparticipant,IdAward,Award
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,2,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,0,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,1,Grammy

In [17]:
# Cargamos la coneixon
# Creare la conexion al motor de BD
engine_dw = db.create_engine("mysql://root:root@127.0.0.1:3310/dw_netflix")
# establesco la conexion
conn_dw = engine_dw.connect()

In [8]:
movie_data = movie_data.rename(columns = {'releaseDate':'releaseMovie', 'Award':'awardMovie'})
movie_data

,movieID,title,releaseMovie,gender,participantName,roleparticipant,IdAward,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,2,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,0,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,1,Grammy

In [9]:
movie_data = movie_data.drop(columns=['IdAward'])

In [10]:
movie_data

,movieID,title,releaseMovie,gender,participantName,roleparticipant,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,Grammy

In [ ]:
# cargar la BD dw_netflix
movie_data.to_sql('dimMovie', conn_dw, if_exists = 'append', index=False)

3

# Cargamos la data de dimnesion USER

In [13]:
users = pd.read_csv('./data/users.csv', sep='|')

users

      idUser     username      country subscription
0    1002331      user123          USA      Premium
1    1002332  gamerGirl97       Canada        Basic
2    1002333   techMaster           UK      Premium
3    1002334    soccerFan       Brazil        Basic
4    1002335    travelBug    Australia      Premium
5    1002336   musicLover       France        Basic
6    1002337     foodie88        Italy      Premium
7    1002338   bookWorm23      Germany        Basic
8    1002339  fitnessJunk       Mexico      Premium
9   10023310    movieBuff        Japan        Basic
10  10023311  artAficiona        Spain      Premium
11  10023312   petLover99  Netherlands        Basic
12  10023313  fashionista   SouthKorea      Premium
13  10023314  codingNinja        India        Basic
14  10023315  natureLover       Norway      Premium
15  10023316  coffeeAddct     Colombia        Basic
16  10023317     beachBum      Bahamas      Premium
17  10023318  skiEnthusst  Switzerland        Basic
18  10023319     homeChef   NewZealand      Premium
19  10023320   yogiMaster     Thailand        Basic

In [14]:
users = users.rename(columns = {'idUser':'userID'})
users

      userID     username      country subscription
0    1002331      user123          USA      Premium
1    1002332  gamerGirl97       Canada        Basic
2    1002333   techMaster           UK      Premium
3    1002334    soccerFan       Brazil        Basic
4    1002335    travelBug    Australia      Premium
5    1002336   musicLover       France        Basic
6    1002337     foodie88        Italy      Premium
7    1002338   bookWorm23      Germany        Basic
8    1002339  fitnessJunk       Mexico      Premium
9   10023310    movieBuff        Japan        Basic
10  10023311  artAficiona        Spain      Premium
11  10023312   petLover99  Netherlands        Basic
12  10023313  fashionista   SouthKorea      Premium
13  10023314  codingNinja        India        Basic
14  10023315  natureLover       Norway      Premium
15  10023316  coffeeAddct     Colombia        Basic
16  10023317     beachBum      Bahamas      Premium
17  10023318  skiEnthusst  Switzerland        Basic
18  10023319     homeChef   NewZealand      Premium
19  10023320   yogiMaster     Thailand        Basic

In [ ]:
users.to_sql('dimUser', conn_dw, if_exists = 'append', index=False)

20

# Cargamos la tabla de echos

In [21]:
user_id = users['userID']
user_id

0      1002331
1      1002332
2      1002333
3      1002334
4      1002335
5      1002336
6      1002337
7      1002338
8      1002339
9     10023310
10    10023311
11    10023312
12    10023313
13    10023314
14    10023315
15    10023316
16    10023317
17    10023318
18    10023319
19    10023320
Name: userID, dtype: int64

In [22]:
movies_id=movies_data['movieID']
movies_id

0    80192187
1    80210920
2    81157374
Name: movieID, dtype: int64

In [24]:
watchs_data = pd.merge(user_id, movies_id, how ='cross')
watchs_data.head()

    userID   movieID
0  1002331  80192187
1  1002331  80210920
2  1002331  81157374
3  1002332  80192187
4  1002332  80210920

In [47]:
import random
from datetime import datetime, timedelta

def gen_rating():
    numero_aleatorio = round(random.uniform(0,5), 1)

    return numero_aleatorio

def gen_timestamps():
    start_date=datetime(2024, 1, 15)
    end_date=datetime(2024, 4, 6)

    random_date = start_date + timedelta(seconds=random.randint(0, int((end_date - start_date).total_seconds())))

    return random_date

In [46]:
gen_timestamps()

datetime.datetime(2024, 3, 31, 12, 26, 11)

In [49]:
watchs_data['rating'] = watchs_data['movieID'].apply(lambda x: gen_rating())

watchs_data

      userID   movieID  rating
0    1002331  80192187     2.7
1    1002331  80210920     4.8
2    1002331  81157374     2.1
3    1002332  80192187     1.1
4    1002332  80210920     0.8
5    1002332  81157374     4.1
6    1002333  80192187     1.4
7    1002333  80210920     1.2
8    1002333  81157374     4.7
9    1002334  80192187     0.6
10   1002334  80210920     3.4
11   1002334  81157374     4.5
12   1002335  80192187     1.2
13   1002335  80210920     3.2
14   1002335  81157374     4.8
15   1002336  80192187     2.5
16   1002336  80210920     2.0
17   1002336  81157374     3.1
18   1002337  80192187     4.1
19   1002337  80210920     0.6
20   1002337  81157374     3.5
21   1002338  80192187     0.9
22   1002338  80210920     0.5
23   1002338  81157374     0.4
24   1002339  80192187     4.7
25   1002339  80210920     4.6
26   1002339  81157374     1.7
27  10023310  80192187     0.3
28  10023310  80210920     2.2
29  10023310  81157374     0.0
30  10023311  80192187     1.2
31  10023311  80210920     3.0
32  10023311  81157374     4.5
33  10023312  80192187     1.2
34  10023312  80210920     2.6
35  10023312  81157374     0.6
36  10023313  80192187     4.8
37  10023313  80210920     3.5
38  10023313  81157374     4.3
39  10023314  80192187     4.2
40  10023314  80210920     4.8
41  10023314  81157374     2.5
42  10023315  80192187     1.9
43  10023315  80210920     3.9
44  10023315  81157374     1.4
45  10023316  80192187     2.8
46  10023316  80210920     1.6
47  10023316  81157374     3.9
48  10023317  80192187     4.5
49  10023317  80210920     3.9
50  10023317  81157374     0.7
51  10023318  80192187     4.1
52  10023318  80210920     4.3
53  10023318  81157374     0.4
54  10023319  80192187     3.7
55  10023319  80210920     3.1
56  10023319  81157374     0.7
57  10023320  80192187     1.2
58  10023320  80210920     4.5
59  10023320  81157374     2.0

In [50]:
watchs_data['timestamp'] = watchs_data['movieID'].apply(lambda x: gen_timestamps())

watchs_data

      userID   movieID  rating           timestamp
0    1002331  80192187     2.7 2024-02-23 18:26:34
1    1002331  80210920     4.8 2024-02-26 12:28:26
2    1002331  81157374     2.1 2024-02-13 00:27:22
3    1002332  80192187     1.1 2024-01-31 07:00:24
4    1002332  80210920     0.8 2024-03-06 05:31:07
5    1002332  81157374     4.1 2024-01-25 12:02:59
6    1002333  80192187     1.4 2024-02-25 04:42:20
7    1002333  80210920     1.2 2024-01-24 06:41:07
8    1002333  81157374     4.7 2024-03-27 16:00:36
9    1002334  80192187     0.6 2024-02-09 14:54:27
10   1002334  80210920     3.4 2024-03-05 14:21:46
11   1002334  81157374     4.5 2024-03-14 12:51:42
12   1002335  80192187     1.2 2024-02-08 03:04:32
13   1002335  80210920     3.2 2024-02-26 15:09:29
14   1002335  81157374     4.8 2024-02-02 07:26:15
15   1002336  80192187     2.5 2024-03-26 11:36:29
16   1002336  80210920     2.0 2024-02-28 06:23:40
17   1002336  81157374     3.1 2024-03-24 15:38:51
18   1002337  80192187     4.1 2024-02-14 13:19:11
19   1002337  80210920     0.6 2024-02-17 20:26:10
20   1002337  81157374     3.5 2024-02-04 14:43:04
21   1002338  80192187     0.9 2024-03-25 10:10:00
22   1002338  80210920     0.5 2024-03-09 10:25:06
23   1002338  81157374     0.4 2024-04-05 07:36:21
24   1002339  80192187     4.7 2024-03-28 11:15:25
25   1002339  80210920     4.6 2024-03-26 12:19:56
26   1002339  81157374     1.7 2024-01-29 11:50:22
27  10023310  80192187     0.3 2024-02-25 20:57:30
28  10023310  80210920     2.2 2024-02-09 11:00:35
29  10023310  81157374     0.0 2024-03-06 03:11:05
30  10023311  80192187     1.2 2024-02-02 05:10:14
31  10023311  80210920     3.0 2024-02-02 13:31:53
32  10023311  81157374     4.5 2024-01-15 14:52:02
33  10023312  80192187     1.2 2024-02-10 10:24:35
34  10023312  80210920     2.6 2024-03-27 02:59:35
35  10023312  81157374     0.6 2024-02-05 22:12:24
36  10023313  80192187     4.8 2024-02-21 21:07:13
37  10023313  80210920     3.5 2024-03-04 04:44:30
38  10023313  81157374     4.3 2024-02-08 18:52:04
39  10023314  80192187     4.2 2024-03-04 16:21:01
40  10023314  80210920     4.8 2024-04-03 15:58:59
41  10023314  81157374     2.5 2024-03-05 09:32:19
42  10023315  80192187     1.9 2024-03-06 10:39:23
43  10023315  80210920     3.9 2024-02-16 05:22:14
44  10023315  81157374     1.4 2024-04-02 03:57:08
45  10023316  80192187     2.8 2024-02-06 23:07:28
46  10023316  80210920     1.6 2024-03-26 23:19:04
47  10023316  81157374     3.9 2024-01-23 06:44:37
48  10023317  80192187     4.5 2024-04-01 08:00:16
49  10023317  80210920     3.9 2024-03-12 08:50:22
50  10023317  81157374     0.7 2024-02-02 20:48:54
51  10023318  80192187     4.1 2024-01-18 15:01:53
52  10023318  80210920     4.3 2024-03-19 07:04:43
53  10023318  81157374     0.4 2024-01-25 15:19:09
54  10023319  80192187     3.7 2024-02-19 12:31:18
55  10023319  80210920     3.1 2024-02-11 16:55:57
56  10023319  81157374     0.7 2024-03-18 14:34:35
57  10023320  80192187     1.2 2024-01-27 04:48:59
58  10023320  80210920     4.5 2024-03-22 08:17:40
59  10023320  81157374     2.0 2024-03-26 20:32:12

In [51]:
watchs_data.to_sql("FactWatchs", conn_dw, if_exists='append', index=False)

60